### ISSUE TITLE
distrans error: MustJoinHandle was not completed upon drop

### ISSUE THREAD

**Issue by Skivling** [cmars/distrans#40]
Uploaded a file, then tried to download it.
Got the same error several times in a row
Will update if it happens with a different file
Installed using the `curl` command on Fedora Linux.
```
$ distrans get VLD0:T0toQzYXFbJS7176lucagE6PA2varvf9H_SAU9C3-rQ   
distrans error: Something went wrong
thread 'tokio-runtime-worker' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/veilid-tools-0.3.0/src/must_join_handle.rs:67:13:
MustJoinHandle was not completed upon drop. Add cooperative cancellation where appropriate to ensure this is completed before drop.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: not ready

Location:
    /home/runner/work/distrans/distrans/src/app.rs:293:21
```

**Comment by Skivling** [comment]
With a different file I keep getting this in logs, and it never auto-quits:
```
2024-04-01T04:54:23.820934Z  WARN distrans_peer::fetcher: fetch block failed, queued for retry err="veilid api error: Timeout"                                     
2024-04-01T04:54:23.820961Z DEBUG distrans_peer::fetcher: task_id=7 fetch="FileBlockFetch { file_index: 0, piece_index: 0, piece_offset: 0, block_index: 5 }"      
2024-04-01T04:54:23.880866Z  WARN distrans_peer::fetcher: fetch block failed, queued for retry err="veilid api error: Timeout"                                     
2024-04-01T04:54:23.880892Z DEBUG distrans_peer::fetcher: task_id=5 fetch="FileBlockFetch { file_index: 0, piece_index: 0, piece_offset: 0, block_index: 3 }"
```

**Comment by cmars** [comment]
Thanks for trying this! The first scenario is unfortunate... seems similar to #36. I need to improve the error handling on the initial connect. One way I've seen that fail is clock skew, though there could be other failure modes.

If the first scenario is repeatable, can you try capturing more detailed logs by setting `RUST_LOG=debug` and pasting the output? This will get quite verbose as it'll pick up veilid-core debug messages, but should help quite a bit.

The second scenario could occur when there's a delay between the seeder (`distrans post` process) rotating private routes, updating the DHT with the new route, and those DHT changes propagating to the fetcher (`distrans get` process). It should eventually settle, but if the seeder isn't running, or is unable to update the DHT, that could cause such a situation.

In both cases (if what I think is happening, is actually happening..) the error messages need to be improved quite a bit.

As a sanity check, can you try fetching a test file I'm currently seeding from my homelab, `distrans get VLD0:cCHB85pEaV4bvRfywxnd2fRNBScR64UaJC8hoKzyr3M`?

**Comment by Skivling** [comment]
For reference I am using Fedora Workstation 39, distrans 0.1.11

This is all just trying to do the sanity check, fetching your file:
Getting your test file crashed, no error message, the TUI just disappeared. This is after a little message in the logs saying 'connected'. 
On retries I can get some errors coming through the logs at the bottom:
`WARN distrans_peer::fetcher: fetch block failed, queued for retry err="veilid api error: timeout"` and also `err="route changed"` - I'm repeatedly getting these errors, inbetween:
`2024-04-03T07:05:04.340479Z DEBUG distrans_peer::fetcher: task_id=0 fetch="FileBlockFetch { file_index: 0, piece_index: 0, piece_offset: 0, block_index: 0 }" `
I can also see that the file is called `itsasecret.jpeg`, and I have the SHA256. But I can't finish getting the file.
Retrying with the `RUST_LOG=debug` and I'm looping through error messages saying `io error: no such file or directory (os error 2)`. So maybe I need to do something on my end with permissions? 

And also where does distrans save the received files to on Linux? So I can check the directory.

I will test the first + second scenarios next.

**Comment by Skivling** [comment]
First scenario testing:
posted a random file 
left it running a bit, then closed that after it finished
distrans get it

Every few seconds I'm getting the same errors as previous:
`err="veilid api error: timeout"` & `err="route changed"`

But I do get an empty file with the right filename in my home folder.
If I try again, with that empty file existing, I end up looping through `no such file or directory`. But I get that even after removing that empty file.

Re-posting a different file (a png this time), it quit with this error:

```
$ distrans post "/home/----/Documents/----------------.png"
distrans error: Something went wrong
thread 'tokio-runtime-worker' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/veilid-tools-0.3.0/src/must_join_handle.rs:93:37:
join error was not a panic, should not poll after abort
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: veilid api error: Generic: allocated route failed to test

Caused by:
    Generic: allocated route failed to test
```

 Where do the logs get written?
 I'll wait to see what you think of all this before doing anything else. Hopefully my comments are easy to follow.

**Comment by cmars** [comment]
Thanks for the detailed feedback and your patience, this is helpful!

Logs aren't persisted anywhere in TUI mode. They should be written somewhere to better support troubleshooting after the fact in TUI mode.

If you disable TUI mode (`distrans --no-ui get|post`), it should be a lot easier to view logs. Here's what I'm seeing from the above:

> WARN distrans_peer::fetcher: fetch block failed, queued for retry err="veilid api error: timeout" and also err="route changed" - I'm repeatedly getting these errors, inbetween:
2024-04-03T07:05:04.340479Z DEBUG distrans_peer::fetcher: task_id=0 fetch="FileBlockFetch { file_index: 0, piece_index: 0, piece_offset: 0, block_index: 0 }" 

This looks like a problem connecting over Veilid.

>Retrying with the RUST_LOG=debug and I'm looping through error messages saying io error: no such file or directory (os error 2). So maybe I need to do something on my end with permissions?

The `io error` is strange. From your later description, seems like it happens when the file already exists (possibly empty), something to investigate!

> And also where does distrans save the received files to on Linux? So I can check the directory.

FIles are written to your current working directory, unless otherwise specified. `distrans get <dht key> [download dir]` will put the file in `[download dir]`.

> So when I said it crashed at the top, that was actually it completing and saving the file.

UX fail in the current release. #33 should help here :pray:.

> Re-posting a different file (a png this time), it quit with this error:

> Error: veilid api error: Generic: allocated route failed to test

Again, Veilid network connection error. Need to make connectivity more resilient, and handle retries more gracefully.

**Comment by cmars** [comment]
@Skivling if you have a chance, could you please try the latest release ([0.3.1](https://github.com/cmars/distrans/releases/tag/distrans-v0.3.1)) and see if the issues above are resolved?

This release has lots of reliability and UX improvements, interested to see how it goes. Thanks!

**Comment by Skivling** [comment]
It worked the first time, although got a lot of this in the middle:
```
2024-06-08T08:01:05.544361Z ERROR distrans_peer::peer::observable: error=remote peer not available: Timeout
2024-06-08T08:01:05.544759Z  WARN distrans_peer::fetcher: fetch block failed, queued for retry err="remote peer not available: Timeout"
```
After a few seconds it reconnected and downloaded file fine.

Also, did I misunderstand the point of this software? Does the person who seeds the file have to be continuously online for it to be retrieved? Because it didn't work when I turned off my seeding instance.

Looks like the problems have been fixed, also the UI&UX is a lot better. Although if it is downloading to the default directory, it says 'fetching filename.ext into .' and doesn't print the actual directory it's saving to.
It would be nice to have a final status message after it's finished downloading as well, like:
Success! FInished fetching _filename_ (`VLD0:8fui3ovnj948fjc3vn49f20f`) and saved into _directory_. 
Also including things like how big the file is, how long it took, and a link to the logs.

**Comment by cmars** [comment]
Thanks for giving this another go!

> Does the person who seeds the file have to be continuously online for it to be retrieved? Because it didn't work when I turned off my seeding instance.

Yes, that's exactly right. Veilid doesn't store the content, it only provides rendezvous and routing for the data transfer. Veilid has discussed a blockstore, but pushing the storage down into the Veilid peer-level is somewhat controversial -- it raises a lot of policy questions of who should be allowed to store what, and how much, and on whose nodes?

Distrans aims to avoid that by answering the content / consent question explicitly rather than implicitly, with a model more like BitTorrent (participants in the swarm only have content they've opted into) than IPFS or Freenet (where nodes might get who-knows-what pulled through them). I think that works nicely as a companion to apps like VeilidChat, where a chat might have attachments, or public distribution of content -- let's say I want to publish and distribute a Veilidchat APK file, a git repo, or an open dataset.

distrans isn't "full-duplex" yet (fetchers can't seed). But they soon will, once the "tracker" capability is added.

Thanks for all your feedback! I've opened a few bugs to track those ideas separately: #101 #102 #103
